spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.13/sell?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.13
    port: 6379
server:
  servlet:
    context-path: /sell
# logging:
#   pattern:
#     console: "%d - %msg%n"
#   # path: /var/log/tomcat/
#   file: /var/log/tomcat/sell.log
#   level:
#     com.cgy.sell.LoggerTest: debug
wechat:
  mpAppId: wx7878cd0d2ef70372 # test account (media platform), usable for getting openid and pushing template message, UNUSABLE FOR WECHAT PAYMENT
  mpAppSecret: ddba84663b2a8b9276657b605ce73a2e # test account (media platform), usable for getting openid and pushing template message, UNUSABLE FOR WECHAT PAYMENT
  openAppId: null # wechat open platform app id, NO OPEN PLATFORM ACCOUNT NOW, WECHAT LOGIN FEATURE UNUSABLE
  openAppSecret: null # wechat open platform app secret, NO OPEN PLATFORM ACCOUNT NOW, WECHAT LOGIN FEATURE UNUSABLE
  mchId: null # wechat pay merchant id, NO PAY ACCOUNT NOW, WECHAT PAYMENT FEATURE UNUSABLE
  mchKey: null  # wechat pay merchant key, NO PAY ACCOUNT NOW, WECHAT PAYMENT FEATURE UNUSABLE
  keyPath: null # used for refunding, not used for invoking payment, format: /path1/path2/wechat_cert/h5.p12, NO PAY ACCOUNT NOW, WECHAT PAYMENT FEATURE UNUSABLE
  notifyUrl: http://cgy.natapp1.cc/sell/pay/notify  # url for wechat platform to notify payment result, NO PAY ACCOUNT NOW, WECHAT PAYMENT FEATURE UNUSABLE
  templateId: # wechat template message id, format: (templateName: templateId)
    orderStatus: nUiXWxlq032si-52RQEPnnR2ofkXCKIg3jgoGTT0EUM
projectUrl:
  wechatMpAuthorize: http://cgy.natapp1.cc
  wechatOpenAuthorize: http://cgy.natapp1.cc
  sell: http://cgy.natapp1.cc
logging:
  level:
    com.cgy.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml
